name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject Discord Webhook URL
        run: |
          # Replace the placeholder in your JavaScript file with the secret
          sed -i "s|__DISCORD_WEBHOOK_URL__|${{ secrets.DISCORD_WEBHOOK_URL }}|g" script.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
